/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#pragma once

#include "Absyn.h"

Graph psGraph(const char *str);
Graph psGraph1(const char *str);
Graph psGraph2(const char *str);
Graph psGraph3(const char *str);
Binding psBinding(const char *str);
GraphBinding psGraphBinding(const char *str);
Vertex psVertex(const char *str);
Name psName(const char *str);
ListName psListName(const char *str);
