/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#ifdef __wasm__
#include "wasm.h"
#else
#include <ctype.h>  /* isspace */
#include <stddef.h> /* size_t */
#include <stdlib.h>
#include <string.h>
#endif

#include "panic.h"

#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '(' || c == '[' || c == '{')
    bufAppendC(c);
  else if (c == ')' || c == ']' || c == '}')
  {
    removeTrailingWhitespace();
    bufAppendC(c);
    bufAppendC(' ');
  }
  else if (c == ',')
  {
    removeTrailingWhitespace();
    bufAppendC(c);
    bufAppendC(' ');
  }
  else if (c == ';')
  {
    removeTrailingWhitespace();
    bufAppendC(c);
    bufAppendC('\n');
    indent();
  }
  else if (c == ' ')
    bufAppendC(c);
  else if (c == 0)
    return;
  else
  {
    bufAppendC(c);
    bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (!isspace(c))
      return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s))
    {
      backup();
      bufAppendS(s);
    }
    else
    {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces(void)
{
  while (cur_ && buf_[cur_ - 1] == ' ')
    --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace(void)
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n'))
    --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine(void)
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1] != '\n')
    bufAppendC('\n');
  indent();
}
char *printGraph(Graph p)
{
  _n_ = 0;
  bufReset();
  ppGraph(p, 0);
  return buf_;
}
char *printBinding(Binding p)
{
  _n_ = 0;
  bufReset();
  ppBinding(p, 0);
  return buf_;
}
char *printGraphBinding(GraphBinding p)
{
  _n_ = 0;
  bufReset();
  ppGraphBinding(p, 0);
  return buf_;
}
char *printVertex(Vertex p)
{
  _n_ = 0;
  bufReset();
  ppVertex(p, 0);
  return buf_;
}
char *printName(Name p)
{
  _n_ = 0;
  bufReset();
  ppName(p, 0);
  return buf_;
}
char *printListName(ListName p)
{
  _n_ = 0;
  bufReset();
  ppListName(p);
  return buf_;
}
char *showGraph(Graph p)
{
  _n_ = 0;
  bufReset();
  shGraph(p);
  return buf_;
}
char *showBinding(Binding p)
{
  _n_ = 0;
  bufReset();
  shBinding(p);
  return buf_;
}
char *showGraphBinding(GraphBinding p)
{
  _n_ = 0;
  bufReset();
  shGraphBinding(p);
  return buf_;
}
char *showVertex(Vertex p)
{
  _n_ = 0;
  bufReset();
  shVertex(p);
  return buf_;
}
char *showName(Name p)
{
  _n_ = 0;
  bufReset();
  shName(p);
  return buf_;
}
char *showListName(ListName p)
{
  _n_ = 0;
  bufReset();
  shListName(p);
  return buf_;
}
void ppGraph(Graph p, int _i_)
{
  switch (p->kind)
  {
  case is_GTensor:
    if (_i_ > 0)
      renderC(_L_PAREN);
    ppGraph(p->u.gTensor_.graph_1, 0);
    renderC('*');
    ppGraph(p->u.gTensor_.graph_2, 1);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_GContext:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderS("context");
    ppString(p->u.gContext_.string_);
    renderS("for");
    ppName(p->u.gContext_.name_, 0);
    renderS("in");
    ppGraph(p->u.gContext_.graph_, 0);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_GNominate:
    if (_i_ > 1)
      renderC(_L_PAREN);
    ppBinding(p->u.gNominate_.binding_, 0);
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GEdgeAnon:
    if (_i_ > 1)
      renderC(_L_PAREN);
    renderC('(');
    ppBinding(p->u.gEdgeAnon_.binding_1, 0);
    renderC(',');
    ppBinding(p->u.gEdgeAnon_.binding_2, 0);
    renderC(')');
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GEdgeNamed:
    if (_i_ > 1)
      renderC(_L_PAREN);
    ppName(p->u.gEdgeNamed_.name_, 0);
    renderC('(');
    ppBinding(p->u.gEdgeNamed_.binding_1, 0);
    renderC(',');
    ppBinding(p->u.gEdgeNamed_.binding_2, 0);
    renderC(')');
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GRuleAnon:
    if (_i_ > 1)
      renderC(_L_PAREN);
    renderC('[');
    renderC('=');
    ppGraph(p->u.gRuleAnon_.graph_1, 0);
    ppGraph(p->u.gRuleAnon_.graph_2, 0);
    renderC(']');
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GRuleNamed:
    if (_i_ > 1)
      renderC(_L_PAREN);
    ppName(p->u.gRuleNamed_.name_, 0);
    renderC('[');
    renderC('=');
    ppGraph(p->u.gRuleNamed_.graph_1, 0);
    ppGraph(p->u.gRuleNamed_.graph_2, 0);
    renderC(']');
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GSubgraph:
    if (_i_ > 1)
      renderC(_L_PAREN);
    ppGraphBinding(p->u.gSubgraph_.graphbinding_, 0);
    if (_i_ > 1)
      renderC(_R_PAREN);
    break;

  case is_GVertex:
    if (_i_ > 2)
      renderC(_L_PAREN);
    ppVertex(p->u.gVertex_.vertex_, 0);
    renderC('|');
    ppGraph(p->u.gVertex_.graph_, 1);
    if (_i_ > 2)
      renderC(_R_PAREN);
    break;

  case is_GVar:
    if (_i_ > 2)
      renderC(_L_PAREN);
    ppIdent(p->u.gVar_.lvar_);
    renderC('|');
    ppGraph(p->u.gVar_.graph_, 1);
    if (_i_ > 2)
      renderC(_R_PAREN);
    break;

  case is_GNil:
    if (_i_ > 3)
      renderC(_L_PAREN);
    renderC('0');
    if (_i_ > 3)
      renderC(_R_PAREN);
    break;
  }
}

void ppBinding(Binding p, int _i_)
{
  switch (p->kind)
  {
  case is_VBind:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderS("let");
    ppIdent(p->u.vBind_.lvar_);
    renderC('=');
    ppVertex(p->u.vBind_.vertex_, 0);
    renderS("in");
    ppGraph(p->u.vBind_.graph_, 2);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;
  }
}

void ppGraphBinding(GraphBinding p, int _i_)
{
  switch (p->kind)
  {
  case is_GBind:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderS("let");
    ppIdent(p->u.gBind_.uvar_);
    renderC('=');
    ppGraph(p->u.gBind_.graph_1, 0);
    renderS("in");
    ppGraph(p->u.gBind_.graph_2, 2);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;
  }
}

void ppVertex(Vertex p, int _i_)
{
  switch (p->kind)
  {
  case is_VName:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderC('<');
    ppName(p->u.vName_.name_, 0);
    renderC('>');
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;
  }
}

void ppName(Name p, int _i_)
{
  switch (p->kind)
  {
  case is_NameWildcard:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderC('_');
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_NameVVar:
    if (_i_ > 0)
      renderC(_L_PAREN);
    ppIdent(p->u.nameVVar_.lvar_);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_NameGVar:
    if (_i_ > 0)
      renderC(_L_PAREN);
    ppIdent(p->u.nameGVar_.uvar_);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_NameQuoteGraph:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderC('@');
    ppGraph(p->u.nameQuoteGraph_.graph_, 0);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;

  case is_NameQuoteVertex:
    if (_i_ > 0)
      renderC(_L_PAREN);
    renderC('@');
    ppVertex(p->u.nameQuoteVertex_.vertex_, 0);
    if (_i_ > 0)
      renderC(_R_PAREN);
    break;
  }
}

void ppListName(ListName listname)
{
  if (listname == 0)
  { /* nil */
  }
  else if (listname->listname_ == 0)
  { /* last */
    ppName(listname->name_, 0);
  }
  else
  { /* cons */
    ppName(listname->name_, 0);
    renderC(',');
    ppListName(listname->listname_);
  }
}

void ppInteger(Integer n)
{
  char tmp[20];
  snprintf(tmp, 20, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d)
{
  char tmp[24];
  snprintf(tmp, 24, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s) { renderS(s); }

void ppUVar(String s) { renderS(s); }

void ppLVar(String s) { renderS(s); }

void shGraph(Graph p)
{
  switch (p->kind)
  {
  case is_GTensor:
    bufAppendC('(');

    bufAppendS("GTensor");

    bufAppendC(' ');

    shGraph(p->u.gTensor_.graph_1);
    bufAppendC(' ');
    shGraph(p->u.gTensor_.graph_2);

    bufAppendC(')');

    break;
  case is_GContext:
    bufAppendC('(');

    bufAppendS("GContext");

    bufAppendC(' ');

    shString(p->u.gContext_.string_);
    bufAppendC(' ');
    shName(p->u.gContext_.name_);
    bufAppendC(' ');
    shGraph(p->u.gContext_.graph_);

    bufAppendC(')');

    break;
  case is_GNominate:
    bufAppendC('(');

    bufAppendS("GNominate");

    bufAppendC(' ');

    shBinding(p->u.gNominate_.binding_);

    bufAppendC(')');

    break;
  case is_GEdgeAnon:
    bufAppendC('(');

    bufAppendS("GEdgeAnon");

    bufAppendC(' ');

    shBinding(p->u.gEdgeAnon_.binding_1);
    bufAppendC(' ');
    shBinding(p->u.gEdgeAnon_.binding_2);

    bufAppendC(')');

    break;
  case is_GEdgeNamed:
    bufAppendC('(');

    bufAppendS("GEdgeNamed");

    bufAppendC(' ');

    shName(p->u.gEdgeNamed_.name_);
    bufAppendC(' ');
    shBinding(p->u.gEdgeNamed_.binding_1);
    bufAppendC(' ');
    shBinding(p->u.gEdgeNamed_.binding_2);

    bufAppendC(')');

    break;
  case is_GRuleAnon:
    bufAppendC('(');

    bufAppendS("GRuleAnon");

    bufAppendC(' ');

    shGraph(p->u.gRuleAnon_.graph_1);
    bufAppendC(' ');
    shGraph(p->u.gRuleAnon_.graph_2);

    bufAppendC(')');

    break;
  case is_GRuleNamed:
    bufAppendC('(');

    bufAppendS("GRuleNamed");

    bufAppendC(' ');

    shName(p->u.gRuleNamed_.name_);
    bufAppendC(' ');
    shGraph(p->u.gRuleNamed_.graph_1);
    bufAppendC(' ');
    shGraph(p->u.gRuleNamed_.graph_2);

    bufAppendC(')');

    break;
  case is_GSubgraph:
    bufAppendC('(');

    bufAppendS("GSubgraph");

    bufAppendC(' ');

    shGraphBinding(p->u.gSubgraph_.graphbinding_);

    bufAppendC(')');

    break;
  case is_GVertex:
    bufAppendC('(');

    bufAppendS("GVertex");

    bufAppendC(' ');

    shVertex(p->u.gVertex_.vertex_);
    bufAppendC(' ');
    shGraph(p->u.gVertex_.graph_);

    bufAppendC(')');

    break;
  case is_GVar:
    bufAppendC('(');

    bufAppendS("GVar");

    bufAppendC(' ');

    shIdent(p->u.gVar_.lvar_);
    bufAppendC(' ');
    shGraph(p->u.gVar_.graph_);

    bufAppendC(')');

    break;
  case is_GNil:

    bufAppendS("GNil");

    break;
  }
}

void shBinding(Binding p)
{
  switch (p->kind)
  {
  case is_VBind:
    bufAppendC('(');

    bufAppendS("VBind");

    bufAppendC(' ');

    shIdent(p->u.vBind_.lvar_);
    bufAppendC(' ');
    shVertex(p->u.vBind_.vertex_);
    bufAppendC(' ');
    shGraph(p->u.vBind_.graph_);

    bufAppendC(')');

    break;
  }
}

void shGraphBinding(GraphBinding p)
{
  switch (p->kind)
  {
  case is_GBind:
    bufAppendC('(');

    bufAppendS("GBind");

    bufAppendC(' ');

    shIdent(p->u.gBind_.uvar_);
    bufAppendC(' ');
    shGraph(p->u.gBind_.graph_1);
    bufAppendC(' ');
    shGraph(p->u.gBind_.graph_2);

    bufAppendC(')');

    break;
  }
}

void shVertex(Vertex p)
{
  switch (p->kind)
  {
  case is_VName:
    bufAppendC('(');

    bufAppendS("VName");

    bufAppendC(' ');

    shName(p->u.vName_.name_);

    bufAppendC(')');

    break;
  }
}

void shName(Name p)
{
  switch (p->kind)
  {
  case is_NameWildcard:

    bufAppendS("NameWildcard");

    break;
  case is_NameVVar:
    bufAppendC('(');

    bufAppendS("NameVVar");

    bufAppendC(' ');

    shIdent(p->u.nameVVar_.lvar_);

    bufAppendC(')');

    break;
  case is_NameGVar:
    bufAppendC('(');

    bufAppendS("NameGVar");

    bufAppendC(' ');

    shIdent(p->u.nameGVar_.uvar_);

    bufAppendC(')');

    break;
  case is_NameQuoteGraph:
    bufAppendC('(');

    bufAppendS("NameQuoteGraph");

    bufAppendC(' ');

    shGraph(p->u.nameQuoteGraph_.graph_);

    bufAppendC(')');

    break;
  case is_NameQuoteVertex:
    bufAppendC('(');

    bufAppendS("NameQuoteVertex");

    bufAppendC(' ');

    shVertex(p->u.nameQuoteVertex_.vertex_);

    bufAppendC(')');

    break;
  }
}

void shListName(ListName listname)
{
  bufAppendC('[');
  while (listname != 0)
  {
    if (listname->listname_)
    {
      shName(listname->name_);
      bufAppendS(", ");
      listname = listname->listname_;
    }
    else
    {
      shName(listname->name_);
      listname = 0;
    }
  }
  bufAppendC(']');
}

void shInteger(Integer i)
{
  char tmp[20];
  snprintf(tmp, 20, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  snprintf(tmp, 24, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shUVar(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}

void shLVar(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s)
    while (*s)
      bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch (c)
  {
  case '\f':
    bufAppendS("\\f");
    break;
  case '\n':
    bufAppendS("\\n");
    break;
  case '\r':
    bufAppendS("\\r");
    break;
  case '\t':
    bufAppendS("\\t");
    break;
  case '\v':
    bufAppendS("\\v");
    break;
  case '\\':
    bufAppendS("\\\\");
    break;
  case '\'':
    bufAppendS("\\'");
    break;
  case '\"':
    bufAppendS("\\\"");
    break;
  default:
    bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for (n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *)malloc(buf_size);
  if (!temp)
  {
    PANIC("OOM");
  }
  if (buf_)
  {
    strncpy(temp, buf_,
            buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;
