/* File generated by the BNF Converter (bnfc 2.9.6). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitGraph(Graph p)
{
  switch(p->kind)
  {
  case is_GTensor:
    /* Code for GTensor Goes Here */
    visitGraph(p->u.gTensor_.graph_1);
    visitGraph(p->u.gTensor_.graph_2);
    break;
  case is_GNominate:
    /* Code for GNominate Goes Here */
    visitBinding(p->u.gNominate_.binding_);
    break;
  case is_GEdgeAnon:
    /* Code for GEdgeAnon Goes Here */
    visitBinding(p->u.gEdgeAnon_.binding_1);
    visitBinding(p->u.gEdgeAnon_.binding_2);
    break;
  case is_GEdgeNamed:
    /* Code for GEdgeNamed Goes Here */
    visitName(p->u.gEdgeNamed_.name_);
    visitBinding(p->u.gEdgeNamed_.binding_1);
    visitBinding(p->u.gEdgeNamed_.binding_2);
    break;
  case is_GRuleAnon:
    /* Code for GRuleAnon Goes Here */
    visitGraph(p->u.gRuleAnon_.graph_1);
    visitGraph(p->u.gRuleAnon_.graph_2);
    break;
  case is_GRuleNamed:
    /* Code for GRuleNamed Goes Here */
    visitName(p->u.gRuleNamed_.name_);
    visitGraph(p->u.gRuleNamed_.graph_1);
    visitGraph(p->u.gRuleNamed_.graph_2);
    break;
  case is_GSubgraph:
    /* Code for GSubgraph Goes Here */
    visitGraphBinding(p->u.gSubgraph_.graphbinding_);
    break;
  case is_GVertex:
    /* Code for GVertex Goes Here */
    visitVertex(p->u.gVertex_.vertex_);
    visitGraph(p->u.gVertex_.graph_);
    break;
  case is_GVar:
    /* Code for GVar Goes Here */
    visitLVar(p->u.gVar_.lvar_);
    visitGraph(p->u.gVar_.graph_);
    break;
  case is_GNil:
    /* Code for GNil Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Graph!\n");
    exit(1);
  }
}

void visitBinding(Binding p)
{
  switch(p->kind)
  {
  case is_VBind:
    /* Code for VBind Goes Here */
    visitLVar(p->u.vBind_.lvar_);
    visitVertex(p->u.vBind_.vertex_);
    visitGraph(p->u.vBind_.graph_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binding!\n");
    exit(1);
  }
}

void visitGraphBinding(GraphBinding p)
{
  switch(p->kind)
  {
  case is_GBind:
    /* Code for GBind Goes Here */
    visitUVar(p->u.gBind_.uvar_);
    visitGraph(p->u.gBind_.graph_1);
    visitGraph(p->u.gBind_.graph_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing GraphBinding!\n");
    exit(1);
  }
}

void visitVertex(Vertex p)
{
  switch(p->kind)
  {
  case is_VName:
    /* Code for VName Goes Here */
    visitName(p->u.vName_.name_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Vertex!\n");
    exit(1);
  }
}

void visitName(Name p)
{
  switch(p->kind)
  {
  case is_NameWildcard:
    /* Code for NameWildcard Goes Here */
    break;
  case is_NameVVar:
    /* Code for NameVVar Goes Here */
    visitLVar(p->u.nameVVar_.lvar_);
    break;
  case is_NameGVar:
    /* Code for NameGVar Goes Here */
    visitUVar(p->u.nameGVar_.uvar_);
    break;
  case is_NameQuoteGraph:
    /* Code for NameQuoteGraph Goes Here */
    visitGraph(p->u.nameQuoteGraph_.graph_);
    break;
  case is_NameQuoteVertex:
    /* Code for NameQuoteVertex Goes Here */
    visitVertex(p->u.nameQuoteVertex_.vertex_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Name!\n");
    exit(1);
  }
}

void visitListName(ListName listname)
{
  while(listname  != 0)
  {
    /* Code For ListName Goes Here */
    visitName(listname->name_);
    listname = listname->listname_;
  }
}

void visitUVar(UVar p)
{
  /* Code for UVar Goes Here */
}
void visitLVar(LVar p)
{
  /* Code for LVar Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}
