#include "Absyn.h"

typedef void (*visitAttrCallback)(Attr p, void *context);
typedef void (*visitAttrNameCallback)(AttrName p, void *context);
typedef void (*visitAttrValCallback)(AttrVal p, void *context);
typedef void (*visitBindingCallback)(Binding p, void *context);
typedef void (*visitGBindCallback)(GraphBinding p, void *context);
typedef void (*visitGraphCallback)(Graph g, void* context);
typedef void (*visitGEdgeAnonCallback)(Graph p, void *context);
typedef void (*visitGEdgeNamedCallback)(Graph p, void *context);
typedef void (*visitGNilCallback)(Graph p, void *context);
typedef void (*visitGNominateCallback)(Graph p, void *context);
typedef void (*visitGRuleAnonCallback)(Graph p, void *context);
typedef void (*visitGRuleNamedCallback)(Graph p, void *context);
typedef void (*visitGSubgraphCallback)(Graph p, void *context);
typedef void (*visitGTensorCallback)(Graph p, void *context);
typedef void (*visitGVarCallback)(Graph p, void *context);
typedef void (*visitGVertexCallback)(Graph p, void *context);
typedef void (*visitIdentCallback)(Ident i, void *context);
typedef void (*visitIntegerCallback)(Integer i, void *context);
typedef void (*visitIsAttrListCallback)(Attr p, void *context);
typedef void (*visitIsAttributeNameCallback)(LVar p, void *context);
typedef void (*visitIsAttributePairCallback)(AttrName p, void *context);
typedef void (*visitIsAttributeValueCallback)(LVar p, void *context);
typedef void (*visitIsGBindCallback)(GraphBinding p, void *context);
typedef void (*visitIsGEdgeAnonCallback)(Graph p, void *context);
typedef void (*visitIsGEdgeNamedCallback)(Graph p, void *context);
typedef void (*visitIsGNilCallback)(Graph p, void *context);
typedef void (*visitIsGNominateCallback)(Graph p, void *context);
typedef void (*visitIsGRuleAnonCallback)(Graph p, void *context);
typedef void (*visitIsGRuleNamedCallback)(Graph p, void *context);
typedef void (*visitIsGSubgraphCallback)(Graph p, void *context);
typedef void (*visitIsGTensorCallback)(Graph p, void *context);
typedef void (*visitIsGVarCallback)(Graph p, void *context);
typedef void (*visitIsGVertexCallback)(Graph p, void *context);
typedef void (*visitIsNameGVarCallback)(Name n, void *context);
typedef void (*visitIsNameQuoteGraphCallback)(Name p, void *context);
typedef void (*visitIsNameQuoteVertexCallback)(Name p, void *context);
typedef void (*visitIsNameVVarCallback)(Name n, void *context);
typedef void (*visitIsNameWildcardCallback)(Name n, void *context);
typedef void (*visitIsVBindCallback)(Binding p, void *context);
typedef void (*visitIsVNameCallback)(Vertex p, void *context);
typedef void (*visitIsEmptyAttrListCallback)(ListAttr p, void *context);
typedef void (*visitListAttrCallback)(ListAttr p, void *context);
typedef void (*visitListNameCallback)(ListName listname, void *context);
typedef void (*visitLVarCallback)(LVar p, void *context);
typedef void (*visitNameCallback)(Name p, void *context);
typedef void (*visitNameGVarCallback)(Name p, void *context);
typedef void (*visitNameVVarCallback)(Name p, void *context);
typedef void (*visitNameWildcardCallback)(Name p, void *context);
typedef void (*visitStringCallback)(String s, void *context);
typedef void (*visitUVarCallback)(UVar p, void *context);
typedef void (*visitVBindCallback)(Binding p, void *context);
typedef void (*visitVertexCallback)(Vertex p, void *context);

typedef struct {
  visitAttrCallback visitAttrCallback;
  visitAttrNameCallback visitAttrNameCallback;
  visitAttrValCallback visitAttrValCallback;
  visitBindingCallback visitBindingCallback;
  visitGBindCallback visitGBindCallback;
  visitGraphCallback visitGraphCallback;
  visitGEdgeAnonCallback visitGEdgeAnonCallback;
  visitGEdgeNamedCallback visitGEdgeNamedCallback;
  visitGNilCallback visitGNilCallback;
  visitGNominateCallback visitGNominateCallback;
  visitGRuleAnonCallback visitGRuleAnonCallback;
  visitGRuleNamedCallback visitGRuleNamedCallback;
  visitGSubgraphCallback visitGSubgraphCallback;
  visitGTensorCallback visitGTensorCallback;
  visitGVarCallback visitGVarCallback;
  visitGVertexCallback visitGVertexCallback;
  visitIdentCallback visitIdentCallback;
  visitIntegerCallback visitIntegerCallback;
  visitIsAttrListCallback visitIsAttrListCallback;
  visitIsAttributeNameCallback visitIsAttributeNameCallback;
  visitIsAttributePairCallback visitIsAttributePairCallback;
  visitIsAttributeValueCallback visitIsAttributeValueCallback;
  visitIsGBindCallback visitIsGBindCallback;
  visitIsGEdgeAnonCallback visitIsGEdgeAnonCallback;
  visitIsGEdgeNamedCallback visitIsGEdgeNamedCallback;
  visitIsGNilCallback visitIsGNilCallback;
  visitIsGNominateCallback visitIsGNominateCallback;
  visitIsGRuleAnonCallback visitIsGRuleAnonCallback;
  visitIsGRuleNamedCallback visitIsGRuleNamedCallback;
  visitIsGSubgraphCallback visitIsGSubgraphCallback;
  visitIsGTensorCallback visitIsGTensorCallback;
  visitIsGVarCallback visitIsGVarCallback;
  visitIsGVertexCallback visitIsGVertexCallback;
  visitIsNameGVarCallback visitIsNameGVarCallback;
  visitIsNameQuoteGraphCallback visitIsNameQuoteGraphCallback;
  visitIsNameQuoteVertexCallback visitIsNameQuoteVertexCallback;
  visitIsNameVVarCallback visitIsNameVVarCallback;
  visitIsNameWildcardCallback visitIsNameWildcardCallback;
  visitIsVBindCallback visitIsVBindCallback;
  visitIsVNameCallback visitIsVNameCallback;
  visitIsEmptyAttrListCallback visitIsEmptyAttrListCallback;
  visitListAttrCallback visitListAttrCallback;
  visitListNameCallback visitListNameCallback;
  visitLVarCallback visitLVarCallback;
  visitNameCallback visitNameCallback;
  visitNameGVarCallback visitNameGVarCallback;
  visitNameVVarCallback visitNameVVarCallback;
  visitNameWildcardCallback visitNameWildcardCallback;
  visitStringCallback visitStringCallback;
  visitUVarCallback visitUVarCallback;
  visitVBindCallback visitVBindCallback;
  visitVertexCallback visitVertexCallback;
} Visitor;
